name: CI/CD Workflow with Docker 2

on: [push]

env:
  TEST: "2"

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Execute Python Script
        run: python script.py

      - name: Build Docker Image
        run: docker build -t youcefalg16/tp4_rendu_1 .

      - name: Run Unit Tests
        run: python test.py

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t youcefalg16/tp4_rendu_1:latest .
